title: Shogo Nakamura
description: Personal website and CV of Shogo Nakamura
show_downloads: false
google_analytics: G-Z691KZMBF9
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag

navbar-links:
  About: "about"
  Education: "education"
  Experience: "experience"
  Research: "research"
  Publications: "publications"
  Conferences: "conferences"
  Others: "others"
  Contact: "contact"
